title: Single Cell Studies
author: Valentine Svensson
logo:
execute:
  execute_notebooks: force
repository:
  url                       : https://github.com/vals/single-cell-studies  # Online location of your book
  branch                    : master  # Which branch of the repository should be used when creating links (optional)
launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: "https://mybinder.org" 
